routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\LigneCommandeController;
use App\Http\Controllers\RolePermissionController;
use Spatie\Permission\Middlewares\RoleMiddleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware("guest")->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home.index');
    Route::get('/add/{id}', [HomeController::class, 'add'])->name('home.add');
    Route::get('/show', [HomeController::class, 'show'])->name('home.show');
    Route::get('/destroy/{id}', [HomeController::class, "destroy"])->name('home.destroy');
    Route::get('/clear', [HomeController::class, "clear"])->name('home.clear');
    Route::get('/search', [HomeController::class, "search"])->name('home.search');
    Route::get("/myOrders", [HomeController::class, "myOrders"])->name("home.myOrders");

    Route::resource("clients", ClientController::class);
    Route::resource("ligneCommandes", LigneCommandeController::class);
    Route::resource("commandes", CommandeController::class)->except('update','show');

});


Route::middleware('auth')->group(function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('roles', RoleController::class);
        Route::get('roles/{role}/assign-permissions', [RolePermissionController::class, 'index'])->name('roles.show');
        Route::post('roles/{role}/assign-permissions', [RolePermissionController::class, 'assign'])->name('roles.assign-permissions');

        Route::resource('permissions', PermissionController::class);
        Route::get('/assign-role', [UserRoleController::class, 'index'])->name('user_roles.index');
        Route::get('{user}/assign-role', [UserRoleController::class, 'create'])->name('user_roles.create');
        Route::post('/{user}/assign-role', [UserRoleController::class, 'assignRoles'])->name('user_roles.store');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    });
    Route::group(['middleware' => ['role:commercial']], function () {
        Route::get('/commandes', [CommandeController::class, "index"])->name('commandes.index');
        Route::get('/commandes/{id}', [CommandeController::class, "show"])->name('commandes.show');
        Route::get('/get-etats/{id}', [CommandeController::class, "getEtats"])->name('get-etats');
        Route::put('/commandes-update/{id}', [CommandeController::class, "update"]);
        Route::post('/commandes/exportCSV', [CommandeController::class, "exportCSV"])->name("commandes.exportCSV");
    });
    Route::group(['middleware' => ['role:magasinier']], function () {
        Route::resource("categories", CategorieController::class);
        Route::resource("produits", ProduitController::class);
        Route::get("categorie/search", [CategorieController::class, 'search'])->name("categories.search");
        Route::get("categorie/clear", [CategorieController::class, 'clear'])->name("categories.clear");

        Route::get("produit/search", [ProduitController::class, 'search'])->name("produits.search");
        Route::get("produit/clear", [ProduitController::class, 'clear'])->name("produits.clear");
    });

});

require __DIR__ . '/auth.php';

resources/views/categories/create.blade.php
 @extends('layouts.layout')
 @section('title','Ajouter une categorie')
 @section('space-work')
 <div class="categorie">
     <h1>Créer une nouvelle categorie</h1>
     <form action="{{route('categories.store')}}" method="POST">
         @csrf
         <div>
         <label for="designation">Designation</label>
         <input type="text" name="designation" id="designation" value="{{old('designation')}}">
         </div>
          <div>
         <label for="description">Description</label>
        <textarea name="description" id="description" cols="30" rows="10" >{{old('designation')}}</textarea>

         </div>
         <div>
             <input class="button" type="submit" value="Ajouter">
         </div>
     </form>
     <div>
         @if($errors->any())
         <ul>
           @foreach($errors->all() as $er)
            <li>{{$er}}</li>

            @endforeach
         </ul>



         @endif
     </div>
 </div>
@endsection

resources/views/categories/edit.blade.php
 @extends('layouts.layout')
 @section('title', 'Modifier une categorie')
 @section('space-work')
<div class="categorie">

    <form action="{{ route('categories.update', ['category' => $cat->id]) }}" method="POST">
        @csrf
        @method('PUT')
        <h3 class="text-center">Modifier la categorie N° {{ $cat->id }}</h3>
        <div>
            <label for="designation">Designation</label>
            <input type="text" name="designation" id="designation" value="{{ old('designation', $cat->designation) }}">
        </div>
        <div>
            <label for="description">Description</label>
            <textarea name="description" id="description" cols="30" rows="10">{{ old('designation', $cat->description) }}</textarea>

        </div>
        <div>
            <input class="btn btn-primary" type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
 @extends('layouts.layout')
 @section('title', 'Gestion des categories')
 @section('space-work')

     <h1>Liste des categories</h1>
     {{-- <form action="{{ route('categories.search') }}" method="get">
         <div>
             <label for="designation">Designation : </label>
             <input type="text" id="designation" name="designation" placeholder="Filtrer par designation"
                 value="{{ $params['designation'] }}">
         </div>
         <div>
             <label for="description">Description : </label>
             <input type="text" id="description" name="description" placeholder="Filtrer par description"
                 value="{{ $params['description'] }}">
         </div>
         <div>
             <input type="submit" value="Appliquer" id="submitFilter">
         </div>
     </form> --}}
     <form class="form-inline" action="{{ route('categories.search') }}" method="get">
        <div class="form-group mx-sm-3 mb-2">
           <label for="designation" class="text-dark mr-2" style="font-size: 1.25em">Designation :</label>
          <input type="text" class="form-control border " id="designation" name="designation" placeholder="Designation" value="{{ $params['designation'] }}">
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <label for="description" class="text-dark mr-2" style="font-size: 1.25em">Description :</label>
          <input type="text" class="form-control border" id="description" name="description" placeholder="Description" value="{{ $params['description'] }}">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Filter</button>
      </form>
     <div class="d-flex justify-content-between my-3">
         <a href="{{ route('categories.create') }}" class="btn btn-primary">Ajouter une nouvelle categorie</a>
         <a href="{{ route('categories.clear') }}" class="btn btn-danger">Supprimer tous les categories</a>
     </div>
     <table id="tbl" class="table center  align-middle text-center caption-top">
         <tr>
             <th>Id</th>
             <th>Designation</th>
             <th>Description</th>
             <th colspan="3">Actions</th>
         </tr>
         @if (isset($notFound))
         <tr>
            <td colspan="6">La list est vide <a href="{{ route("categories.index") }}">Retourner a la list</a></td>
         </tr>
         @else
         @foreach ($categories as $cat)
             <tr>
                 <td>{{ $cat->id }}</td>
                 <td>{{ $cat->designation }}</td>
                 <td>{{ $cat->description }}</td>
                 <td><a class="btn btn-secondary" href="{{ route('categories.show', ['category' => $cat->id]) }}">Details</a></td>
                 <td><a class="btn btn-success" href="{{ route('categories.edit', ['category' => $cat->id]) }}">Modifier</a></td>
                 <td>
                     <form action="{{ route('categories.destroy', ['category' => $cat->id]) }}" method="POST">
                         @method('DELETE')
                         @csrf
                         <input class="btn btn-danger" type="submit" value="Supprimer"
                             onclick="return confirm('voulez-vous supprimer cette categorie?')">
                     </form>
                 </td>
             </tr>
         @endforeach
     </table>
     <div>
         {{ $categories->links() }}
     </div>
     @endif
 @endsection

resources/views/categories/show.blade.php
 @extends('layouts.layout')
 @section('title','Detail d \'une categorie')
 @section('space-work')
    <a class="btn btn-primary my-3" href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection