routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\LigneCommandeController;
use App\Http\Controllers\RolePermissionController;
use Spatie\Permission\Middlewares\RoleMiddleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware("guest")->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home.index');
    Route::get('/add/{id}', [HomeController::class, 'add'])->name('home.add');
    Route::get('/show', [HomeController::class, 'show'])->name('home.show');
    Route::get('/destroy/{id}', [HomeController::class, "destroy"])->name('home.destroy');
    Route::get('/clear', [HomeController::class, "clear"])->name('home.clear');
    Route::get('/search', [HomeController::class, "search"])->name('home.search');
    Route::get("/myOrders", [HomeController::class, "myOrders"])->name("home.myOrders");

    Route::resource("clients", ClientController::class);
    Route::resource("ligneCommandes", LigneCommandeController::class);
    Route::resource("commandes", CommandeController::class)->except('update','show');

});


Route::middleware('auth')->group(function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('roles', RoleController::class);
        Route::get('roles/{role}/assign-permissions', [RolePermissionController::class, 'index'])->name('roles.show');
        Route::post('roles/{role}/assign-permissions', [RolePermissionController::class, 'assign'])->name('roles.assign-permissions');

        Route::resource('permissions', PermissionController::class);
        Route::get('/assign-role', [UserRoleController::class, 'index'])->name('user_roles.index');
        Route::get('{user}/assign-role', [UserRoleController::class, 'create'])->name('user_roles.create');
        Route::post('/{user}/assign-role', [UserRoleController::class, 'assignRoles'])->name('user_roles.store');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    });
    Route::group(['middleware' => ['role:commercial']], function () {
        Route::get('/commandes', [CommandeController::class, "index"])->name('commandes.index');
        Route::get('/commandes/{id}', [CommandeController::class, "show"])->name('commandes.show');
        Route::get('/get-etats/{id}', [CommandeController::class, "getEtats"])->name('get-etats');
        Route::put('/commandes-update/{id}', [CommandeController::class, "update"]);
        Route::post('/commandes/exportCSV', [CommandeController::class, "exportCSV"])->name("commandes.exportCSV");
    });
    Route::group(['middleware' => ['role:magasinier']], function () {
        Route::resource("categories", CategorieController::class);
        Route::resource("produits", ProduitController::class);
        Route::get("categorie/search", [CategorieController::class, 'search'])->name("categories.search");
        Route::get("categorie/clear", [CategorieController::class, 'clear'])->name("categories.clear");

        Route::get("produit/search", [ProduitController::class, 'search'])->name("produits.search");
        Route::get("produit/clear", [ProduitController::class, 'clear'])->name("produits.clear");
    });

});

require __DIR__ . '/auth.php';

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'image'
    ];
    public function categorie(){
       return  $this->belongsTo(Categorie::class);
    }
    public function commandes(){
        return $this->belongsToMany(Commande::class,"lignecommandes")->withPivot("qte");
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $produitsBuilder = Produit::query();
        $notFound = false;

        $designation = $request->query("filter_designation");
        $categorie = $request->query("filter_categorie");
        $prix_u_min = $request->query("prix_u_min");
        $prix_u_max = $request->query("prix_u_max");
        $quantite = $request->query("filter_quantite_stock");


        if ($designation != null) {
            $produitsBuilder->where('designation', 'like', '%' . $designation . '%');
        }
        if ($categorie != null) {
            $produitsBuilder->where('categorie_id', $categorie);
        }
        if ($prix_u_min != null) {
            $produitsBuilder->where('prix_u', '>=', $prix_u_min);
        }

        if ($prix_u_max != null) {
            $produitsBuilder->where('prix_u', '<=', $prix_u_max);
        }

        if ($quantite != null) {
            $produitsBuilder->where('quantite_stock', '=', $quantite);
        }
        $params = [
            "filter_designation" => $designation,
            "filter_categorie" => $categorie,
            "prix_u_min" => $prix_u_min,
            "prix_u_max" => $prix_u_max,
            "filter_quantite_stock" => $quantite
        ];

        if ($produitsBuilder->count() == 0 && Produit::all()->count() != 0) {
            $notFound = "Aucun produit trouve";
        } elseif ($produitsBuilder->count() < Produit::all()->count()) {
            $notFound = " ";
        }

        $produits = $produitsBuilder->paginate(5)->appends($params);

        $categories = Categorie::all();
        return view("produits.index", [
            'produits' => $produits,
            "categories" => $categories,
            "notFound" => $notFound,
            "params" => $params
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */


    public function create()
    {
        $categories = Categorie::all();
        return view("produits.create", compact("categories"));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            "designation" => "required|unique:produits,designation",
            "prix_u" => "required",
            "quantite_stock" => "required",
            "categorie_id" => "required",
            "image" => "image|mimes:jpeg,png,jpeg,gif,svg|max:2048"
        ]);

        if ($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("products/images", "public");
            $validateData["image"] = $imagePath;
        }
        Produit::create($validateData);
        return redirect()->route("produits.index");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $produit = Produit::find($id); #
        return view('produits.show')->with("produit", $produit);

        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $produit = Produit::find($id);
        $categories = Categorie::all();
        return view('produits.edit', compact('produit', "categories"));

        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $produitsOnStock=session()->get("produits_on_stock",[]);
        
        foreach($produitsOnStock as $key => $value){
            if ($value["id"] == $id && $value["quantite"] > $request->quantite_stock && $request->quantite_stock!=0) {
                $produitsOnStock[$key]["quantite"] = $request->quantite_stock;
                session()->put("produits_on_stock", $produitsOnStock);   
                break;
            }
        }

        $validateData = $request->validate([
            "designation" => "required|unique:produits,designation," . $id,
            "prix_u" => "required",
            "quantite_stock" => "required",
            "categorie_id" => "required",
            "image" => "image|mimes:jpeg,png,jpeg,gif,svg|max:2048"
        ]);

        if ($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("products/images", "public");
            $validateData["image"] = $imagePath;
        }
        $produit = Produit::find($id);
        $produit->update($validateData);
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');
    }

    public function clear()
    {
        DB::table("produits")->delete();
        return redirect()->route("produits.index");
    }
}

resources/views/produits/create.blade.php
@extends('layouts.layout')
@section('title', 'cree un produit')
@section('space-work')
    <form class="produit" action="{{ route('produits.store') }}" method="post"  enctype="multipart/form-data">
        @csrf
        <h3 class="text-center">Ajouter un produit</h3>
        <div>
            <label for="designation">Designation</label>
            <input type="text" name="designation" value="{{old("designation")}}">
        </div>
        <div>
            <label for="prix_u">Prix unitaire (DH)</label>
            <input type="number" min="1" name="prix_u" id="prix_u" value="{{old("prix_u")}}">
        </div>
        <div>
            <label for="quantite_stock">Quantite on stock</label>
            <input type="number" min="0"  name="quantite_stock" id="quantite_stock" value="{{old("quantite_stock")}}">
        </div>
        <div>
            <label for="categorie_id">N° Categorie</label>
            <select name="categorie_id" id="categorie_id">
                <option value="">Select la categorie...</option>
                @foreach ($categories as $categorie)
                    <option value="{{ $categorie->id }}">{{ $categorie->id }} - {{ $categorie->designation }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <input type="file" name="image" id="image" accept="image/*" onchange="showImage(this)">
            <img src="" alt="" id="productImg">
        </div>
        <div>
            <input class="button" type="submit" value="Ajouter">
            <input class="button"  type="reset" value="Vider">
        </div>

    </form>
    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li>{{$error}}</li>
        @endforeach
    </ul>
    @endif
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.layout')
@section('title', 'Modifier un produit')
@section('space-work')
<div class="produit">
    <form action="{{ route('produits.update', ['produit' => $produit->id]) }}" method="post" enctype="multipart/form-data">
        @method('put')
        @csrf
        <h3 class="text-center">Modifier un produit</h3>
            <div>
                <label for="designation">Designation</label>
                <input type="text" name="designation" value="{{ $produit->designation }}">
            </div>
            <div>
                <label for="prix_u">Prix unitaire</label>
                <input type="number" min="1" name="prix_u" id="prix_u" value="{{ $produit->prix_u }}">
                <span>DH</span>

            </div>
            <div>
                <label for="quantite_stock">Quantite on stock</label>
                <input type="number" min="0" name="quantite_stock" id="quantite_stock"
                    value="{{ $produit->quantite_stock }}">
            </div>
            <div>
                <label for="image">Image</label>
                <input type="file" name="image" id="image" value="{{ asset($produit->image) }}" accept="image/*" onchange="showImage(this)">
                <img class="img-pro" src="{{ asset("storage/".$produit->image) }}" alt="{{$produit->designation}}" id="productImg">
            </div>
            <div>
                <label for="categorie_id">N° Categorie</label>
                <select name="categorie_id" id="categorie_id">
                    <option value="{{ $produit->categorie_id }}" default>{{ $produit->categorie_id }} -
                        {{ $produit->categorie->designation }}</option>
                    @foreach ($categories as $cat)
                        @if ($cat->id !== $produit->categorie_id)
                            <option value="{{ $cat->id }}">{{ $cat->id }} - {{ $cat->designation }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
            <div>
                <input class="button" type="submit" value="Modifier">
                <input class="button" type="reset" value="Vider">
            </div>
        </form>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
</div>
@endsection

resources/views/produits/index.blade.php
@extends('layouts.layout')
@section('title', 'Gestion des produits')
@section('space-work')
    <h1>Liste des Produits</h1>
        {{-- <div>
            <label for="prix_u">Prix : </label>
            <input type="hidden" name="prix_u_min" id="prix_u_min" value="0">
            <input type="hidden" name="prix_u_max" id="prix_u_max" value="1000">
            <!--   ----------------------   -->
            <span id="lower-price">0</span>MAD
            <div id="price-range-slider">
            </div>
            <span id="upper-price">1000</span>MAD
        </div> --}}

        <!--   ----------------------   -->
        <form class="form-inline" action="{{ route('produits.index') }}" method="get">
            <div class="form-group mx-sm-3 mb-2">
               <label for="filter_designation" class="text-dark mr-2" style="font-size: 1.25em">Designation :</label>
              <input type="text" class="form-control border " id="filter_designation" name="filter_designation" placeholder="Designation" value="{{ $params['filter_designation'] }}">
            </div>
            <div class="form-group mx-sm-3 mb-2">
              <label for="filter_categorie" class="text-dark mr-2" style="font-size: 1.25em">Categorie :</label>
              <select class="form-control border" style="width: 20em" name="filter_categorie" id="filter_categorie">
                <option value="">choisir une categprie...</option>
                @foreach ($categories as $cat)
                    <option value="{{ $cat->id }}">{{ $cat->designation }}</option>
                @endforeach
            </select>
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <label for="filter_quantite_stock" class="text-dark mr-2" style="font-size: 1.25em">Quantite en stock :</label>
               <input type="text" class="form-control border " id="filter_quantite_stock" name="filter_quantite_stock" placeholder="Quantite en stock" value="{{ $params['filter_quantite_stock'] }}">
             </div>
            <button type="submit" class="btn btn-primary mb-2">Filter</button>
          </form>
          <div class="d-flex justify-content-between my-3">
            <a href="{{ route('produits.create') }}" class="btn btn-primary">Ajouter une nouvelle produit</a>
            <a href="{{ route('produits.clear') }}" class="btn btn-danger">Supprimer tous les produits</a>
        </div>
    <table id="tbl" class="table center  align-middle text-center caption-top">

        <tr>
            <th>ID</th>
            <th>Designation</th>
            <th>Prix unitaire</th>
            <th>Quantite on stock</th>
            <th>N° Categorie</th>
            <th colspan="3">Action</th>
        </tr>
        @if ($notFound)
        <tr>
            <td colspan="6">La list est vide <a href="{{ route("produits.index") }}">Retourner a la list</a></td>
         </tr>
        @else
        @foreach ($produits as $produit)
            <tr>
                <td>{{ $produit->id }}</td>
                <td>{{ $produit->designation }}</td>
                <td>{{ $produit->prix_u }}</td>
                <td>{{ $produit->quantite_stock }}</td>
                <td>{{ $produit->categorie_id }} - {{ $produit->Categorie->designation }}</td>
                <td><a class="btn btn-secondary" href="{{ route('produits.show', ['produit' => $produit->id]) }}">Details</a></td>
                <td><a class="btn btn-success" href="{{ route('produits.edit', ['produit' => $produit->id]) }}">Modifier</a></td>
                <td>
                    <form action="{{ route('produits.destroy', ['produit' => $produit->id]) }}" method="post">
                        @method('DELETE')
                        @csrf
                        <input type="submit"
                            onclick="return confirm('voulez vous supprimer le produit ayant lid {{ $produit->id }}')"
                            class="btn btn-danger" value="supprimer">
                    </form>
                </td>
            </tr>
        @endforeach
        @endif
    </table>
    <div>
        {{ $produits->links() }}
    </div>
@endsection

resources/views/produits/show.blade.php
@extends('layouts.layout')
@section('title','Detail d \'une categorie')
@section('space-work')
   <a class="btn btn-primary my-3" href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
   <div class="produit">
       <form>
        <h3 class="text-center">Detail de le produit Num {{$produit->id}}</h3>
        <p><strong>Designation:</strong> {{$produit->designation}}</p>
        <p><strong>Prix unitaire:</strong> {{$produit->prix_u}}</p>
        <p><strong>Quantite on stock:</strong> {{$produit->quantite_stock}}</p>
        <p><strong>N° Categorie:</strong> {{$produit->categorie_id}}</p>
        <p><strong>image</strong></p>
        <img class="img-pro" src="{{asset("storage/".$produit->image)}}" alt="{{$produit->designation}}">
    </form>
   </div>
@endsection