routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\LigneCommandeController;
use App\Http\Controllers\RolePermissionController;
use Spatie\Permission\Middlewares\RoleMiddleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware("guest")->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home.index');
    Route::get('/add/{id}', [HomeController::class, 'add'])->name('home.add');
    Route::get('/show', [HomeController::class, 'show'])->name('home.show');
    Route::get('/destroy/{id}', [HomeController::class, "destroy"])->name('home.destroy');
    Route::get('/clear', [HomeController::class, "clear"])->name('home.clear');
    Route::get('/search', [HomeController::class, "search"])->name('home.search');
    Route::get("/myOrders", [HomeController::class, "myOrders"])->name("home.myOrders");

    Route::resource("clients", ClientController::class);
    Route::resource("ligneCommandes", LigneCommandeController::class);
    Route::resource("commandes", CommandeController::class)->except('update','show');

});


Route::middleware('auth')->group(function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('roles', RoleController::class);
        Route::get('roles/{role}/assign-permissions', [RolePermissionController::class, 'index'])->name('roles.show');
        Route::post('roles/{role}/assign-permissions', [RolePermissionController::class, 'assign'])->name('roles.assign-permissions');

        Route::resource('permissions', PermissionController::class);
        Route::get('/assign-role', [UserRoleController::class, 'index'])->name('user_roles.index');
        Route::get('{user}/assign-role', [UserRoleController::class, 'create'])->name('user_roles.create');
        Route::post('/{user}/assign-role', [UserRoleController::class, 'assignRoles'])->name('user_roles.store');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    });
    Route::group(['middleware' => ['role:commercial']], function () {
        Route::get('/commandes', [CommandeController::class, "index"])->name('commandes.index');
        Route::get('/commandes/{id}', [CommandeController::class, "show"])->name('commandes.show');
        Route::get('/get-etats/{id}', [CommandeController::class, "getEtats"])->name('get-etats');
        Route::put('/commandes-update/{id}', [CommandeController::class, "update"]);
        Route::post('/commandes/exportCSV', [CommandeController::class, "exportCSV"])->name("commandes.exportCSV");
    });
    Route::group(['middleware' => ['role:magasinier']], function () {
        Route::resource("categories", CategorieController::class);
        Route::resource("produits", ProduitController::class);
        Route::get("categorie/search", [CategorieController::class, 'search'])->name("categories.search");
        Route::get("categorie/clear", [CategorieController::class, 'clear'])->name("categories.clear");

        Route::get("produit/search", [ProduitController::class, 'search'])->name("produits.search");
        Route::get("produit/clear", [ProduitController::class, 'clear'])->name("produits.clear");
    });

});

require __DIR__ . '/auth.php';

app/Models/Role.php
<?php

namespace App\Models;

use Spatie\Permission\Models\Role as SpatieRole;
use Spatie\Permission\Traits\HasPermissions;

class Role extends SpatieRole
{
    use HasPermissions;

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
         public function index()
         {
              $roles = Role::all();
              return view('roles.index', compact('roles'));
         }


         public function create()
         {
              return view('roles.create');
         }


         public function store(Request $request)
         {
              $validated = $request->validate([
              'name' => 'required|unique:roles|max:255',
              ]);
              $role = Role::create(['name' => $validated['name']]);
              return redirect()->route('roles.index')
              ->with('success','Role created successfully.');
         }


         public function show(Role $role)
         {
              return view('roles.show',compact('role'));
         }


         public function edit(Role $role)
         {
             return view('roles.edit',compact('role'));
         }


         public function update(Request $request, Role $role)
         {
                $validated = $request->validate([
                'name' => 'required|unique:roles,name,'.$role->id.'|max:255',
                 ]);
                $role->name = $validated['name'];
                $role->save();
                return redirect()->route('roles.index')
                ->with('success','Role updated successfully');
         }


         public function destroy(Role $role)
         {
              $role->delete();
              return redirect()->route('roles.index')
              ->with('success','Role deleted successfully');
         }
}

resources/views/roles/create.blade.php
 @extends('layouts.layout')
 @section('title','Ajouter une role')
 @section('space-work')
 <div class="container">
     <h1>Créer une nouvelle role</h1>
     <form action="{{route('roles.store')}}" method="POST">
         @csrf
         <div>
         <label for="name">Name</label>
         <input type="text" name="name" id="name" value="{{old('name')}}">
         </div>
         <div>
             <input class="button" type="submit" value="Ajouter">
         </div>
     </form>
     <div>
         @if($errors->any())
         <ul>
           @foreach($errors->all() as $er)
            <li>{{$er}}</li>

            @endforeach
         </ul>



         @endif
     </div>
 </div>
@endsection

resources/views/roles/edit.blade.php
 @extends('layouts.layout')
 @section('title', 'Modifier une role')
 @section('space-work')
<div class="container">

    <form action="{{ route('roles.update', ['role' => $role->id]) }}" method="POST">
        @csrf
        @method('PUT')
        <h3 class="text-center">Modifier la role N° {{ $role->id }}</h3>
        <div>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ old('name', $role->name) }}">
        </div>
        <div>
            <input class="btn btn-primary" type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.layout')
@section('title','Permissions')
@section('space-work')
    <div class="container">
        <div class="d-flex justify-content-between my-3">
            <a href="{{ route('roles.create') }}" class="btn btn-primary">Ajouter une nouvelle categorie</a>
        </div>
         <table id="tbl" class="table center  align-middle text-center caption-top">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created At</th>
                <th colspan="2">Actions</th>
            </tr>
            @if (isset($notFound))
            <tr>
               <td colspan="6">La list est vide <a href="{{ route("roles.index") }}">Retourner a la list</a></td>
            </tr>
            @else
            @foreach ($roles as $role)
                <tr>
                    <td>{{ $role->id }}</td>
                    <td>{{ $role->name }}</td>
                    <td>{{ $role->created_at }}</td>
                    <td><a class="btn btn-success" href="{{ route('roles.edit', ['role' => $role->id]) }}">Modifier</a></td>
                    <td><a class="btn btn-success" href="{{ route('roles.show', ['role' => $role->id]) }}">give premission</a></td>
                    <td>
                        <form action="{{ route('roles.destroy', ['role' => $role->id]) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <input class="btn btn-danger" type="submit" value="Supprimer"
                                onclick="return confirm('voulez-vous supprimer cette role?')">
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {{-- <div>
            {{ $roles->links() }}
        </div> --}}
        @endif
    </div>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.layout')

@section('title', 'Modifier un rôle')

@section('space-work')

<div class="container">
    <div class="card">
        <div class="card-header">Affecter des permissions au rôle {{ $role->name }}</div>
        <div class="card-body">
            <form action="{{ route('roles.assign-permissions', ['role' => $role->id]) }}" method="POST">
                @csrf

                <div class="row">
                    <div class="col-md-6">
                        <h5>Permissions disponibles</h5>
                        <ul>
                            @foreach ($permissions as $permission)
                            {{-- {{ dd($role->getPermissionNames()) }} --}}
                                @if (!$role->hasPermissionTo($permission))
                                    <li>
                                        <label>
                                            <input type="checkbox" name="permissions[]" value="{{ $permission->id }}">
                                            {{ $permission->name }}
                                        </label>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                    </div>

                    <div class="col-md-6">
                        <h5>Permissions assignées</h5>
                        <ul>
                            @foreach ($permissions as $permission)
                                @if ($role->hasPermissionTo($permission))
                                    <li>
                                        <label>
                                            <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" checked>
                                            {{ $permission->name }}
                                        </label>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col">
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                        <a href="{{ route('roles.index') }}" class="btn btn-secondary">Annuler</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@endsection